print("pallavi first class pytho")
print("2nd line")
print("pallavi first class pytho")
print("2nd line")
print("pallavi first class pytho")
print("2nd line")
print("pallavi first class pytho")
print("2nd line")